import { aboreto, geistMono, geistSans, notoSerifDisplay } from "@/fonts";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: {
    template: "%s ||  La Cabane",
    default: "La Cabane",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${aboreto.variable} ${notoSerifDisplay.variable} h-full font-sans antialiased`}
    >
      <body className="flex min-h-full flex-col bg-primary-base">
        <div className="sticky top-0 z-20">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
